spring.application.name=app
server.port=8083

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=app_user
spring.datasource.password=####
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

logging.level.org.springframework.security=DEBUG

jwt.secret=6G8qL2mP9wR4xT7vY1aN5kC8dF3hJ6sQ9zX2bV4nM7pR1tY5uW8eA3cD6fG9hK2
#jwt.expiration=86400000
jwt.expiration=300000